version: '3.8'

services:

  web:
    build: .
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 80:8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - API_KEY=${API_KEY}
